<p STYLE="font-size: 20px"><b>NumPy</b> (Numeric Python) is een package die erg nuttig is voor wiskundige scripts. De library biedt functies die gebruik maken van (multi-dimensionale) arrays. Deze hebben vele voordelen t.o.v. Python lists. Zo zijn ze compacter, sneller, gemakkelijker en efficiënter.</p>

Nuttige websites:
1. https://numpy.org/doc/stable/
2. https://numpy.org/doc/stable/reference/
3. https://www.datacamp.com/community/tutorials/python-numpy-tutorial

Simpele demonstratie waarom **NumPy** veel handiger *en* sneller is dan standaard Python. 
(Dit voorbeeld kan je makkelijk zelf uitvoeren - leuk om te proberen na deze les!):
* http://zwmiller.com/blogs/why_numpy_is_so_great.html

<img src="arrays.png" align="left">

# 1D array

In [1]:
import numpy as np

a1 = np.array([7,2,9,10])
a2 = np.array([2,3,4,5])
print ("array1:", a1)
print ("array2:", a2)
print ("a1*a2:", a1*a2)
print ("Aantal dimensies array1:", a1.ndim)
print ("Shape array1:", a1.shape)
print ("Size array1:", a1.size)
print ("Som, min en max van array1:", a1.sum(), a1.min(), a1.max())
print ("a1[2] =>", a1[2])
print ("a1[:2] =>", a1[:2])
print ("a1[2:] =>", a1[2:])

array1: [ 7  2  9 10]
array2: [2 3 4 5]
a1*a2: [14  6 36 50]
Aantal dimensies array1: 1
Shape array1: (4,)
Size array1: 4
Som, min en max van array1: 28 2 10
a1[2] => 9
a1[:2] => [7 2]
a1[2:] => [ 9 10]


# 2D array

In [2]:
a3 = np.array([[5.2, 3.0, 4.5],
               [9.1, 0.1, 0.3]])
print ("Aantal dimensies array3:", a3.ndim)
print ("Shape array3:", a3.shape) #2 rijen, 3 kolommen
print ("Size array3:", a3.size)
print ("Dtype array3:", a3.dtype)
print ("a3[1,2] =>", a3[1,2])
print ("a3[1,:2] =>", a3[1,:2])
print ("a3[:,:2] =>", a3[:,:2])

#Een for-loop is niet heel gebruikelijk; er zijn vaak betere/snellere alternatieven
#for row in a3:
#    print ("Rij max:",row.max())

#Alternatief voor het maximum per rij:
print("Maximum per rij:", a3.max(axis=1))

#Of het maximum per kolom:
print("Maximum per kolom:", a3.max(axis=0))

#Of de som per rij:
print("Som per rij:", a3.sum(axis=1))

#Loopen door elementen
for element in a3.flat:
    print ("Element:", element)


Aantal dimensies array3: 2
Shape array3: (2, 3)
Size array3: 6
Dtype array3: float64
a3[1,2] => 0.3
a3[1,:2] => [9.1 0.1]
a3[:,:2] => [[5.2 3. ]
 [9.1 0.1]]
Maximum per rij: [5.2 9.1]
Maximum per kolom: [9.1 3.  4.5]
Som per rij: [12.7  9.5]
Element: 5.2
Element: 3.0
Element: 4.5
Element: 9.1
Element: 0.1
Element: 0.3


# 3D array

In [3]:
# 3D array
a4 = np.array([[[1,2], [4,3], [7,4]],
               [[2,3], [9,6], [7,5]],
               [[1,5], [3,4], [0,2]],
               [[9,4], [6,5], [9,8]]])
print ("Aantal dimensies array4:", a4.ndim)
print ("Shape array4:", a4.shape) #4 rijen, 3 kolommen, diepte=2
print ("Size array4:", a4.size)
print ("a4[2,1,0] =>", a4[2,1,0])


Aantal dimensies array4: 3
Shape array4: (4, 3, 2)
Size array4: 24
a4[2,1,0] => 3


# Aanmaken verschillende arrays

In [4]:
# Een array met range van 10 tot 20 met stapgrootte 2
a5 = np.arange(10, 20, 2)
print ("a5:", a5)

# Een array met 3 rijen en 4 kolommen met nullen
a6 = np.zeros((3,4),dtype=np.int16)
print ("a6:", a6)
# Bij elk element 2 bij optellen
a6 += 2
print ("a6:", a6)
# Optellen bij aanmaak array
a6 = np.zeros((3,4),dtype=np.int16) + 2
print ("a6:", a6)

# Random arrays
a7 = np.random.random((2,3)) # 2 rijen en 3 kolommen
print ("a7:", a7)
a8 = np.random.randint(1, 10, size=(3,2)) # 3 rijen en 2 kolommen
print ("a8:", a8)

a5: [10 12 14 16 18]
a6: [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
a6: [[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
a6: [[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
a7: [[0.44309926 0.80662384 0.65800224]
 [0.54349764 0.45162253 0.83391361]]
a8: [[7 7]
 [7 2]
 [1 7]]


# Bestand als input voor arrays

In [5]:
a9 = np.loadtxt('data.txt', skiprows=1)
print ("a9:", a9)
a10 = np.loadtxt('data.txt', skiprows=1, usecols=(0,2))
print ("a10:", a10)

a9: [[0.2536 0.1008 0.3857]
 [0.4839 0.4536 0.3561]
 [0.1292 0.6875 0.5929]
 [0.1781 0.3049 0.8928]
 [0.6253 0.3486 0.8791]]
a10: [[0.2536 0.3857]
 [0.4839 0.3561]
 [0.1292 0.5929]
 [0.1781 0.8928]
 [0.6253 0.8791]]


# Reshape, transpose en stack

In [6]:
# Reshape van 1D naar 2D-array met 20 rijen
a11 = np.arange(100)
print ("a11:", a11, a11.shape)
a11 = a11.reshape(20, 5)
#of:
#a11 = a11.reshape(20,-1)
print ("a11 reshape:", a11, a11.shape)

# Transpose
a12 = a11.T
print ("a12 transpose:", a12, a12.T.shape)

# Stack
a13 = np.random.random((2,2))
print ("a13:", a13)
a14 = np.random.random((2,2))
print ("a14:", a14)
a15 = np.hstack((a13,a14))
print ("a15 hstack:", a15, a15.shape)
a16 = np.vstack((a13,a14))
print ("a14 vstack:", a16, a16.shape)


a11: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] (100,)
a11 reshape: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]] (20, 5)
a12 transpose: [[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
 [ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
 [ 2  7 12 17 22 27 32 37 42 47 52 57 62 67 72 77 82 87 92 97]
 [ 3  8 13 18 23 28 33 38 43 48 53 58 63 68 73 78 83 88 93 98]
 [ 4  9 14 19 24 29 34 39 44 49 5

# Indexing en boolean masking

In [7]:
# Indexing
a17 = np.array(["a", "b", "c", "d", "e"])
print (a17)
indices = np.array([1, 0, 1, 2, 4, 3, 4, 2, 0])
print (a17[indices])

a18 = np.random.randint(1, 100, size=(5,5))
print(a18)
#welke zijn groter dan 70?
mask = a18 > 70 #array van True/False waarden
print(mask)
print(a18[mask]) #mask wordt gebruikt om nieuwe (1D) array te genereren

['a' 'b' 'c' 'd' 'e']
['b' 'a' 'b' 'c' 'e' 'd' 'e' 'c' 'a']
[[48 13 37 37 57]
 [41 89 58 41 13]
 [52 87 35 87 70]
 [48 50 75 78 59]
 [10 41 42 51 66]]
[[False False False False False]
 [False  True False False False]
 [False  True False  True False]
 [False False  True  True False]
 [False False False False False]]
[89 87 87 75 78]
